services:

  app:
    container_name: idiario-app
    build:
      context: .
      args:
        RUBY_VERSION: 2.6.6
        GEM_VERSION: 3.3.22
        BUNDLER_VERSION: 2.4.22
    command: ./script/start
    volumes:
      - .:/app
      - box:/box
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      REDIS_URL: redis://idiario-redis
    ports:
      - ${DOCKER_APP_PORT:-80}:80
      - ${DOCKER_APP_SSL_PORT:-443}:443

  postgres:
    container_name: idiario-postgres
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: idiario_development
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT:-5432}:5432

  redis:
    container_name: idiario-redis
    image: redis:7-alpine
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379

volumes:
  box:
  postgres:
